# Generated by Django 3.2.3 on 2021-09-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_todo_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_active',
            new_name='is_verifed',
        ),
    ]
